-------------------------------------------------------------------------------
Test set: com.zhy.poolTest.DatasourceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.545 s <<< FAILURE! - in com.zhy.poolTest.DatasourceTest
connectTest(com.zhy.poolTest.DatasourceTest)  Time elapsed: 0.539 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in com/zhy/mapper/UserMapper.java (best guess)
### The error may involve com.zhy.mapper.UserMapper.findUsernameById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.zhy.poolTest.DatasourceTest.connectTest(DatasourceTest.java:33)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
### The error may exist in com/zhy/mapper/UserMapper.java (best guess)
### The error may involve com.zhy.mapper.UserMapper.findUsernameById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.zhy.poolTest.DatasourceTest.connectTest(DatasourceTest.java:33)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.zhy.poolTest.DatasourceTest.connectTest(DatasourceTest.java:33)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.zhy.poolTest.DatasourceTest.connectTest(DatasourceTest.java:33)

